
services:
###> shopware/core ###
  database:
    ports:
      - "3306"
###< shopware/core ###

###> symfony/mailer ###
  mailer:
    container_name: artiss-mailer
    image: axllent/mailpit
    networks:
      - artiss
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/api/v1/info"]
      start_period: 10s
      interval: 15s
      timeout: 3s
      retries: 3
###< symfony/mailer ###

###> shopware/elasticsearch ###
  opensearch:
    ports:
      - "9200"
###< shopware/elasticsearch ###
